services:
  app-nginx:
    container_name: app-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html
    networks:
      - app-network

  app-php-fpm:
    container_name: app-php-fpm
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  app-redis:
    image: redis:latest
    container_name: app-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
