services:
  app-nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html
    networks:
      - app-network

  app-php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

networks:
  app-network: